### Using SupportVectorMachine algorithm for digit prediction on MNIST data

The data set used is a simplified version of the original MNIST, and it's divided in 2 dataset: mnist_train and mnist_test.

In [1]:
#! pip install scikit-learn
#! pip install pandas
#! pip install numpy

In [2]:
import pandas as pd

# Load training and testing data
train_data = pd.read_csv('mnist_train.csv')
test_data = pd.read_csv('mnist_test.csv')
train_data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [3]:
train_data.describe()

label      1x1      1x2      1x3      1x4      1x5      1x6  \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       4.453933      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889270      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           1x7      1x8      1x9  ...         28x19         28x20  \
count  60000.0  60000.0  60000.0  ...  60000.000000  60000.000000   
mean       0.0      0.0      0.0  ...      0.200433      0.088867   
std        0.0      0.0      0.0  ...      6.042472      3.956189   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

              28x21         28x22         28x23       28x24    28x25    28x26  \
count  60000.000000  60000.000000  60000.000000  60000.0000  60000.0  60000.0   
mean       0.045633      0.019283      0.015117      0.0020      0.0      0.0   
std        2.839845      1.686770      1.678283      0.3466      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
max      253.000000    253.000000    254.000000     62.0000      0.0      0.0   

         28x27    28x28  
count  60000.0  60000.0  
mean       0.0      0.0  
std        0.0      0.0  
min        0.0      0.0  
25%        0.0      0.0  
50%        0.0      0.0  
75%        0.0      0.0  
max        0.0      0.0  

[8 rows x 785 columns]

In [4]:
test_data.describe()

label      1x1      1x2      1x3      1x4      1x5      1x6  \
count  10000.000000  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0   
mean       4.443400      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.895865      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           1x7      1x8      1x9  ...         28x19         28x20  \
count  10000.0  10000.0  10000.0  ...  10000.000000  10000.000000   
mean       0.0      0.0      0.0  ...      0.179300      0.163600   
std        0.0      0.0      0.0  ...      5.674149      5.736072   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    253.000000    253.000000   

              28x21       28x22    28x23    28x24    28x25    28x26    28x27  \
count  10000.000000  10000.0000  10000.0  10000.0  10000.0  10000.0  10000.0   
mean       0.052600      0.0006      0.0      0.0      0.0      0.0      0.0   
std        2.420004      0.0600      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
25%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
50%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
75%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
max      156.000000      6.0000      0.0      0.0      0.0      0.0      0.0   

         28x28  
count  10000.0  
mean       0.0  
std        0.0  
min        0.0  
25%        0.0  
50%        0.0  
75%        0.0  
max        0.0  

[8 rows x 785 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Preprocess the data
X_train = train_data.drop(columns=['label'])
y_train = train_data['label']
X_test = test_data.drop(columns=['label'])
y_test = test_data['label']

X_train

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0        0    0    0    0    0    0    0    0    0     0  ...      0      0   
1        0    0    0    0    0    0    0    0    0     0  ...      0      0   
2        0    0    0    0    0    0    0    0    0     0  ...      0      0   
3        0    0    0    0    0    0    0    0    0     0  ...      0      0   
4        0    0    0    0    0    0    0    0    0     0  ...      0      0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
59995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 784 columns]

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
from sklearn.svm import SVC

# Train the Support Vector Machine model
svm_model = SVC(kernel='rbf', gamma='scale')  # You can adjust parameters like kernel type and regularization
svm_model.fit(X_train_scaled, y_train)

SVC()

In [8]:
# Display the parameters of the SVM model
print("Support Vector Machine (SVM) Parameters:")
#print("Coefficients (weights):", svm_model.coef_) if using a linear kernel
print("Intercept (bias):", svm_model.intercept_)
print("Support vectors:", svm_model.support_vectors_)
print("Number of support vectors for each class:", svm_model.n_support_)
print("Support vector indices:", svm_model.support_)
print("Dual coefficients:", svm_model.dual_coef_)
print("Classes:", svm_model.classes_)
print("Kernel:", svm_model.kernel)
print("Gamma:", svm_model.gamma)
print("Regularization parameter (C):", svm_model.C)

Support Vector Machine (SVM) Parameters:
Intercept (bias): [ 0.17757855 -0.74425242 -0.59016187 -0.36323133 -0.48418699 -0.69821417
 -0.72566473 -0.26282653 -0.43992064 -0.83323032 -0.73548996 -0.44539362
 -0.62365496 -0.76408214 -0.8128406  -0.33746663 -0.57054382  0.26421414
  0.55226834  0.42560995  0.12116076 -0.04605375  0.61009065  0.42054948
  0.30720721  0.20740333 -0.12092824 -0.29945704  0.44580329  0.20052713
 -0.15205296 -0.43188758 -0.53936171  0.10208699 -0.19943361 -0.30947836
 -0.45331236  0.36899051  0.01358696 -0.14986777  0.50209732  0.29712295
  0.60595822  0.52348742 -0.22572429]
Support vectors: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Number of support vectors for each class: [ 875  633 1893 1895 1474 1833 1348 1793 1851 1953]
Support vector indices: [   68   216   232 ... 59969 59973 59992]
Dual coefficients: [[ 0.03824154  0.          0.         ..

In [9]:
# Predict labels for the testing data
y_pred_svm = svm_model.predict(X_test_scaled)

# Calculate accuracy
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy (SVM):", accuracy_svm)

Accuracy (SVM): 0.966


In [10]:
# Select the features of the first row of the training data
first_row_features = X_train_scaled[[0]]

# Predict the label using the trained logistic regression model
predicted_label = svm_model.predict(first_row_features)

# Print the predicted label
print("Predicted Label:", predicted_label)

Predicted Label: [5]
